server:
  port: 8090
  servlet:
    context-path: /

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/familytree?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1 from dual
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  session:
    timeout: 3600
    jdbc:
      schema: schema-mysql.sql
    store-type: jdbc
  jpa:
    hibernate:
      ddl-auto: none
  resources:
    add-mappings: true
  security:
    user:
      name: admin
      password: admin

security:
  oauth2:
    client:
      client-id: family_tree
      client-secret: family_tree
      access-token-uri: http://localhost/oauth/token
      user-authorization-uri: http://localhost/oauth/authorize
    resource:
      user-info-uri: http://localhost/user/me

logging:
  level: INFO

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: com.baomidou.mybatisplus.extension.handlers.EnumTypeHandler
  type-enums-package: com.starfire.familytree.enums
  global-config:
    db-config:
      field-strategy: ignored